services:
  api:
    container_name: api
    build: .
    env_file:
      - .env
    environment: # override .env since we want to use the redis from below
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
      - 80:80
    networks:
      - redis-network
    restart: unless-stopped

  redis:
    extends:
      file: compose-dev.yaml
      service: redis
    ports: !override []
    networks:
      - redis-network

networks:
  redis-network:
